const buttons = document.querySelectorAll('.btn');
const blueSound = document.getElementById('blue-sound');
const redSound = document.getElementById('red-sound');
const greenSound = document.getElementById('green-sound');
const yellowSound = document.getElementById('yellow-sound');
const wrongSound = document.getElementById('wrong-sound')
let arrayUserInput =[];
let arrayAutoGenerated =[];
let count=0; //count is set to 0


//start game
document.addEventListener('keydown', startGame);

function startGame() {
  if (count === 0) {
    count += 1;
    currentLevel();
    generatedArray();
  }
}
//update level
function currentLevel() {
  if (count > 0) {
      document.getElementById('level-title').textContent = `Level ${count}`;
  }
}

function generatedArrayEffects() {
  // Get the last color in the array
  const color = arrayAutoGenerated[arrayAutoGenerated.length - 1];
  const button = document.querySelector(`.btn.${color}`);

  if (button) {
    setTimeout(() => {
      button.classList.add('pressed');

      // sound based on color
      if (color == 'green') {
        greenSound.play();
      }
      if (color == 'red') {
        redSound.play();
      }
      if (color == 'blue') {
        blueSound.play();
      }
      if (color == 'yellow') {
        yellowSound.play();
      }


      setTimeout(() => {
        button.classList.remove('pressed');
      }, 100);
    }, (arrayAutoGenerated.length - 1) * 500);
  }
}

//creating random array
function getRandomItem(randomArray) {
  const index = Math.floor(Math.random() * randomArray.length);
  return randomArray[index];
}

//array with random color after each level
function generatedArray() {
  if(count > 0) {
      const randomButton = getRandomItem(buttons);
      const randomColor = randomButton.id;
      arrayAutoGenerated.push(randomColor);
      console.log(arrayAutoGenerated);
      generatedArrayEffects();
  }
}


//an array of the color clicked
buttons.forEach(button => {
  button.addEventListener('click', function (e) {
    if (count > 0) {
      button.classList.add('pressed');

      let clickedColor;
      if (button.classList.contains('green')) {
        clickedColor = 'green';
        greenSound.play();
      } else if (button.classList.contains('red')) {
        clickedColor = 'red';
        redSound.play();
      } else if (button.classList.contains('yellow')) {
        clickedColor = 'yellow';
        yellowSound.play();
      } else if (button.classList.contains('blue')) {
        clickedColor = 'blue';
        blueSound.play();
      }

      // Push to array only if the color is correct
      if (clickedColor) {
        arrayUserInput.push(clickedColor);
        console.log(arrayUserInput);
        compareArrays();
      }

      setTimeout(() => {
        button.classList.remove('pressed');
      }, 100); // Adjust the duration as needed
    }
  });
});

function compareArrays() {
  for (let i = 0; i < arrayUserInput.length; i++) {
    if (arrayUserInput[i] !== arrayAutoGenerated[i]) {
      console.log('Arrays do not match! Restarting game...');
      restartGame();
      return; // Exit the function early
    }
  }

  //when the input matches and they have the same size level is incremented
  if (arrayUserInput.length === arrayAutoGenerated.length) {
    console.log('Arrays match! Incrementing count...');
    count += 1;
    arrayUserInput = [];
    currentLevel();
    generatedArray();
  }
}

function restartGame() {
  // Reset all game variables and arrays
  arrayUserInput = [];
  arrayAutoGenerated = [];
  count = 0;
  document.getElementById('level-title').textContent = "Game Over! Press any key to start";
  wrongSound.play();
}