const buttons = document.querySelectorAll('.btn');
let arrayUserInput =[];
let arrayAutoGenerated =[];
let count=0; //count is set to 0

document.addEventListener('keydown', startGame);

function startGame() {
  if (count === 0) {
    count += 1;
    currentLevel();
    generatedArray();
  }
}

function currentLevel() {
  if (count > 0) {
      document.getElementById('level-title').textContent = `Level ${count}`;
  }
}

//creating random array
function getRandomItem(randomArray) {
  const index = Math.floor(Math.random() * randomArray.length);
  return randomArray[index];
}

//array with random color after each click
function generatedArray() {
  if(count > 0) {
      const randomButton = getRandomItem(buttons);
      const randomColor = randomButton.id;
      arrayAutoGenerated.push(randomColor);
      console.log(arrayAutoGenerated);
      //compareArrays(); 
  }
}


//an array of the color clicked
buttons.forEach(button => {
  button.addEventListener('click', function (e) {
    if (count > 0) {
      if (button.classList.contains('green')) {
        arrayUserInput.push('green');
      } else if (button.classList.contains('red')) {
        arrayUserInput.push('red');
      } else if (button.classList.contains('yellow')) {
        arrayUserInput.push('yellow');
      } else if (button.classList.contains('blue')) {
        arrayUserInput.push('blue');
      }
      console.log(arrayUserInput);
      compareArrays();

      if (count > 0) {
        count += 1;
        currentLevel();
        generatedArray();
      }
    }
  });
});

function compareArrays() {
  if (arrayUserInput.length === arrayAutoGenerated.length) {
    const arraysMatch = arrayUserInput.every((value, index) => value === arrayAutoGenerated[index]);

    if (arraysMatch) {
      console.log('Arrays match!');
      // Continue the game or move to the next level
    } else {
      restartGame();
      // call restartGame function
    }
  }
}

function restartGame() {
  // Reset all game variables and arrays
  arrayUserInput = [];
  arrayAutoGenerated = [];
  count = 0;
  document.getElementById('level-title').textContent = "Game Over! Press any key to start";
}